package ProxmodCron::Render;

use strict;
use warnings;

use ProxmodCron::Config;
use ProxmodCron::Registry;
use ProxmodCron::Spec;

# Definitions -> the text of one /etc/cron.d file.
#
# Pure: render() takes a store and a node name and returns a string. It touches
# no filesystem, which is why most of the test suite points here.
#
# Two cron rules are load-bearing and are handled in exactly one place, below:
#
#   * cron hands the command to $SHELL, so every argv element is shell-quoted
#     here and nowhere else.
#   * '%' in a crontab command means "newline, and everything after is stdin".
#     An unescaped one silently truncates the job. It is escaped after quoting,
#     because cron reads the line before the shell does.

our $VERSION = '202608.17.0';

our $EXEC = ProxmodCron::Config::prefix() . '/usr/lib/proxmod-cron/proxmod-cron-exec';

our $BANNER = 'Generated by proxmod-cron. Do not edit - changes are overwritten.';

our $PATH = '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin';

my %FILENAME = (
    cluster => 'proxmod-cron-cluster',
    node => 'proxmod-cron-node',
);

# The anchor: the conffile whose single line runs proxmod-cron-sync every
# minute, which is the whole convergence mechanism. It is not generated and it
# is not a job anyone scheduled, but it is unambiguously ours — so it is named
# here, beside the files it produces, rather than spelled out again in each
# place that has to recognise it.
our $ANCHOR = 'proxmod-cron';

=head2 filename($scope)

The generated file's base name. No '.' in it, ever: cron ignores a file in
/etc/cron.d whose name contains a dot, and the failure is completely silent.

=cut

sub filename {
    my ($scope) = @_;
    return $FILENAME{$scope} || die "unknown scope '$scope'\n";
}

sub path {
    my ($scope) = @_;
    return ProxmodCron::Config::cron_d() . '/' . filename($scope);
}

=head2 anchor_filename() / anchor_path()

The anchor conffile. One definition, shared by the inventory (which must not
report our own file as somebody else's) and by C<proxmod-cronctl doctor> (which
checks it exists, because without it nothing renders and nothing runs).

=cut

sub anchor_filename {
    return $ANCHOR;
}

sub anchor_path {
    return ProxmodCron::Config::cron_d() . '/' . $ANCHOR;
}

=head2 render($scope, $store, $nodename)

The whole file. Returns undef when nothing renders for this node, which is the
signal to remove the file rather than leave an empty one behind.

=cut

sub render {
    my ($scope, $store, $nodename) = @_;

    my @lines;
    my @body;
    my $count = 0;

    for my $id (sort keys %{ $store->{jobs} || {} }) {
        my $job = ProxmodCron::Config::effective($scope, $store, $id);
        next if !$job;

        next if $scope eq 'cluster' && !ProxmodCron::Config::targets_node($job, $nodename);

        push @body, render_job($job);
        $count++;
    }

    return undef if !$count;

    push @lines, "# $BANNER";
    push @lines, '# Source: ' . ProxmodCron::Config::file_for($scope)
        . '   Scope: ' . $scope
        . (defined($nodename) ? "   Node: $nodename" : '')
        . "   Jobs: $count";
    push @lines, 'SHELL=/bin/sh';
    push @lines, "PATH=$PATH";
    push @lines, 'MAILTO=' . _mailto($store);
    push @lines, '';

    return join("\n", @lines, @body) . "\n";
}

# Cron's default is to mail a job's output to its user, which on a hypervisor
# means mail nobody reads. Emptying it is only defensible because
# proxmod-cron-exec captures that output into journald instead — the two
# decisions are one decision. An administrator who does want the mail sets
# `mailto` on the store.
sub _mailto {
    my ($store) = @_;

    my $mailto = defined($store->{mailto}) ? $store->{mailto} : '';
    return '""' if $mailto eq '';

    # Anything that is not a plain address is dropped rather than rendered: this
    # line is read by cron itself, and a newline in it would inject a job.
    return '""' if $mailto !~ /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\z/;

    return $mailto;
}

=head2 render_job($job)

The comment header and the crontab line for one effective job, as a list of
lines. A job whose plugin will not load renders as comments naming the missing
type — never silently dropped, and never executed with a guessed command.

=cut

sub render_job {
    my ($job) = @_;

    my @out;

    my $label = "# job: $job->{id} ($job->{type})";
    $label .= ' [' . $job->{owner} . ']' if $job->{origin} eq 'extension' && $job->{owner};
    $label .= ' - ' . _comment_text($job->{comment}) if defined $job->{comment} && $job->{comment} ne '';
    $label .= ' - DISABLED' if !$job->{enabled};

    push @out, $label;

    my $argv = eval { ProxmodCron::Registry::build_command($job->{type}, $job) };
    if (!$argv) {
        my $why = $@ || "job type '$job->{type}' produced no command\n";
        chomp $why;
        push @out, '# UNAVAILABLE: ' . _comment_text($why);
        push @out, '';
        return @out;
    }

    my $command = join(' ', map { quote($_) } @{ wrap($job, $argv) });

    my $line = join("\t", $job->{schedule}, $job->{user}, escape_percent($command));

    # A disabled job stays in the file as a comment rather than disappearing, so
    # `cat /etc/cron.d/proxmod-cron-node` still shows everything that is defined.
    push @out, ($job->{enabled} ? $line : "#$line");
    push @out, '';

    return @out;
}

=head2 wrap($job, $argv, %opts)

The argv cron actually runs: the job's own command, inside the run wrapper when
anything at all has to happen around it.

Two things put a job in the wrapper. Tracking, which is what it was built for.
And the cluster scope, which needs the quorum guard and possibly the tick lease —
decisions that can only be made at fire time, on the node that is about to run,
and so cannot live in a rendered file.

An untracked cluster job therefore gains a wrapper it did not have before, but
with C<--no-record>: it is guarded, and otherwise runs exactly as it used to,
with no run lock and no history.

C<manual =E<gt> 1> omits C<--once>. C<proxmod-cronctl run> passes it, because an
operator who names a node and a moment has already made the choice the lease
exists to make, and must not lose a race to a scheduled tick.

Shared with C<proxmod-cronctl run> so that running a job by hand runs the same
thing the schedule does — including the tracking, which is what puts a manual
run in the same history as a scheduled one.

=cut

sub wrap {
    my ($job, $argv, %opts) = @_;

    my $cluster = ($job->{scope} || '') eq 'cluster';

    return [@$argv] if !$job->{track} && !$cluster;

    my @wrapper = ($EXEC, $job->{scope}, $job->{id});
    push @wrapper, '--no-output' if !$job->{keep_output};

    # The type travels with the argv rather than being looked up in the store at
    # run time, so PROXMOD_CRON_TYPE always describes the definition that
    # produced this line. A store read would label a run with a type the argv
    # does not match, in the window between an edit and the next sync.
    push @wrapper, '--type', $job->{type} if defined $job->{type};

    if ($cluster) {
        push @wrapper, '--require-quorum';

        # The schedule travels on the line for the same reason the type does: the
        # tick both nodes race for has to be derived from the definition that
        # produced this line, not from whatever the store says a minute later.
        push @wrapper, '--once', '--schedule', $job->{schedule}
            if ($job->{run_on} || 'all') eq 'any' && !$opts{manual};
    }

    push @wrapper, '--no-record' if !$job->{track};

    return [@wrapper, '--', @$argv];
}

# A comment is still a line in a file cron parses. A newline would end the
# comment and start something else.
sub _comment_text {
    my ($text) = @_;
    my $out = defined($text) ? $text : '';
    $out =~ s/[\r\n]+/ /g;
    $out =~ s/\s+\z//;
    return $out;
}

=head2 quote($arg)

Shell-quote one argv element. Left bare when it is unambiguously safe, because
the readability of the generated file is the reason native cron was chosen as
the engine.

=cut

sub quote {
    my ($arg) = @_;

    $arg = '' if !defined $arg;

    return q{''} if $arg eq '';
    return $arg if $arg =~ m{\A[A-Za-z0-9_./:=@,+-]+\z};

    # Single quotes protect everything except a single quote, which is closed,
    # escaped and reopened.
    my $out = $arg;
    $out =~ s/'/'\\''/g;

    return "'$out'";
}

=head2 escape_percent($text)

Escape '%' for cron. Applied to the finished command, after quoting: cron
processes the line before the shell sees it, so quoting does not protect a '%'.

=cut

sub escape_percent {
    my ($text) = @_;
    my $out = defined($text) ? $text : '';
    $out =~ s/%/\\%/g;
    return $out;
}

=head2 summary($scope, $store, $nodename)

What GET jobs returns per row, minus the permission flags the API adds: the
rendered command, whether it renders on this node at all, and the next run.

Sharing this with the renderer is deliberate — the command the UI shows and the
command cron runs are built by the same code path, so they cannot drift.

=cut

sub summary {
    my ($scope, $store, $nodename) = @_;

    my @rows;

    for my $id (sort keys %{ $store->{jobs} || {} }) {
        my $job = ProxmodCron::Config::effective($scope, $store, $id);
        next if !$job;

        my $row = {
            id => $id,
            scope => $scope,
            type => $job->{type},
            origin => $job->{origin},
            enabled => $job->{enabled},
            schedule => $job->{schedule},
            user => $job->{user},
            track => $job->{track},
            keep_output => $job->{keep_output},
        };

        $row->{owner} = $job->{owner} if defined $job->{owner};
        $row->{comment} = $job->{comment} if defined $job->{comment};
        $row->{nodes} = $job->{nodes} if defined $job->{nodes};
        $row->{run_on} = $job->{run_on} if defined $job->{run_on};

        $row->{renders} = ($scope eq 'node'
            || ProxmodCron::Config::targets_node($job, $nodename)) ? 1 : 0;

        my $argv = eval { ProxmodCron::Registry::build_command($job->{type}, $job) };
        if ($argv) {
            $row->{command} = join(' ', map { quote($_) } @$argv);
        } else {
            my $why = $@ || 'no command';
            chomp $why;
            $row->{unavailable} = $why;
        }

        my ($ok, $why) = ProxmodCron::Spec::validate($job->{schedule});
        if ($ok) {
            my $next = eval { ProxmodCron::Spec::next_run($job->{schedule}) };
            $row->{next_run} = $next if defined $next;
        } else {
            $row->{schedule_error} = $why;
        }

        push @rows, $row;
    }

    return \@rows;
}

1;
